### ISSUE TITLE
1.i Measure Work Effort

### ISSUE THREAD

**Issue by WebSebBerlin** [PragTob/TracketyTrack#20]
Measuring the work effort of a user story is used to track the working effort required for a user story, compare it to the estimated working effort and get more experienced. The work effort of a user story is measured by measuring the time the user story was “active” (from starting to completing, excluding paused).

Priority: MEDIUM
Estimation: 3

**Comment by PragTob** [comment]
Hey Flo, warum hast du die noch nicht geschlossen, was fehlt denn noch? (hab nur den Commit gesehen)

Frohe Weihnachten!
