### ISSUE TITLE
1.k.i Overview Deleted User Stories

### ISSUE THREAD

**Issue by WebSebBerlin** [PragTob/TracketyTrack#22]
**Giving an overview of the user stories** supports the project team members to stay up to date with all user stories. A user of the system can get an overview of all user stories.

**Overview deleted user stories** A user of the system can get an overview of all deleted user stories.

Priority: LOW
Estimation: 1

**Comment by PragTob** [comment]
Accidentally did this one as well while doing the the delete user story user story - uppsi ;-P
