### ISSUE TITLE
2.c Invite People to Project

### ISSUE THREAD

**Issue by WebSebBerlin** [PragTob/TracketyTrack#30]
A user should be able to invite people to join the project via entering their email address.

Priority: MEDIUM
Estimation: 3

**Comment by PragTob** [comment]
Inviting people via email requires setting up a mail server, I'd suspect that this is too much overhead for just inviting a couple of users. This way it is faster for the admin to send this email himself.

Or any other ideas?

**Comment by PragTob** [comment]
As discussed in the team meeting this is dropped until we got more urgent email features or move to being a platform service.
