### ISSUE TITLE
2.e Accept Project Team Members

### ISSUE THREAD

**Issue by WebSebBerlin** [PragTob/TracketyTrack#32]
Accept Project Team Members to join the project. If the TracketyTrack website of a project is publicly accessible you might not want grant access to the system to everybody who registers as they might finish all your user stories or mess other things up. That is why it would be an optional feature that you have to accept the registration of users before they can start to use the system. A user should be able to accept the registration only of those users that he knows and really wants to give access to the team.

Priority: MEDIUM
Estimation: 2

**Comment by PragTob** [comment]
One hell of a ride due to various authentication problems but it is done now.
