### ISSUE TITLE
3.f Show User’s Gravatar

### ISSUE THREAD

**Issue by WebSebBerlin** [PragTob/TracketyTrack#41]
Gravatar stands for Globally Recognizable Avatar. A gravatar is linked to your email address, so if a user has a gravatar we can just display it and otherwise a generic image. Display the gravatar of a user.

Priority: LOW
Estimation: 1

**Comment by PragTob** [comment]
Easy as pie.

**Comment by WebSebBerlin** [comment]
Hast du gravatar drin??? Dann kann ich das ja gleich noch in user profile
einbauen :)

Am 02.01.12 00:48 schrieb "Tobias Pfeiffer" unter
<reply+i-2331776-02e764c0b875c6657e3ea09573fc6d0c67a0338a-1197959@reply.git
hub.com>:

**Comment by PragTob** [comment]
Ich hab den schon rudimentär ins user profile eingebaut. pull halt mal und shau dir das show an. Methode heißt gravatar_for und findeste im users_helper.rb - da kannste dann noch css Klassen etc. hinzufügen wenn du willst (und die default größe umsetzen bzw. sie manuell setzen)
