### ISSUE TITLE
4.g Number of User Stories

### ISSUE THREAD

**Issue by WebSebBerlin** [PragTob/TracketyTrack#48]
A user should be able to see the overall number of user stories.
A user should be able to see the number of completed stories.
A user should be able to see the number of uncompleted user stories.
A user should be able to see the number of deleted user stories.
A user should be able to see the number of user stories, that are currently work in progress.

Priority: LOW
Estimation: 1

**Comment by jharzmann** [comment]
numbers are shown at the navigation menu (header) of the user story page
