### ISSUE TITLE
7.c.ii Show Status of Last Build

### ISSUE THREAD

**Issue by WebSebBerlin** [PragTob/TracketyTrack#75]
As a user, I want to see the status of the last build on the TracketyTrack page of my project, so I know whether all tests currently pass as it should be.

Priority: LOW
Estimation: 2

**Comment by PragTob** [comment]
Lol I thought this was also included in #76 - well we already got that and it was never ever worth the combined 3 points (the hardest thing about it was figuring out stubbing)
