### ISSUE TITLE
7.c.iii Link to Travis CI

### ISSUE THREAD

**Issue by WebSebBerlin** [PragTob/TracketyTrack#76]
As a user I want to have a link to the Travis CI page of my project showing me all the latest builds.

Priority: LOW
Estimation: 1

**Comment by PragTob** [comment]
Please be aware that whoever does this story has to parse the repository url (if present), check whether it is a github url and then check if they are associated to TravisCI (maybe Travis has an API to check whether there is a TravisCI account for that)

Be aware that there could be different URLs inserted into the repository url page, such as:
https://github.com/PragTob/TracketyTrack
git@github.com:PragTob/TracketyTrack.git
https://PragTob@github.com/PragTob/TracketyTrack.git
