### ISSUE TITLE
3.c Login

### ISSUE THREAD

**Issue by WebSebBerlin** [PragTob/TracketyTrack#8]
Login is important that only project team members can update and manipulate the project data. A user can log in to authenticate, there is no access to the system without logging in.

Priority: HIGH
Estimation: 4

**Comment by PragTob** [comment]
Um yeah the push from 40minutes ago solved this issue.  Some important methods:

```
sign_in(user) # signs a user in
signed_in? # is a user currently signed in?
sign_out # signs the current user aus
current_user # returns the currently signed in user
authenticate # used for before actions to see whether a user is signed in or not
```
